[package]
name = "vis_rs"
version = "0.1.0"
authors = ["BjÃ¸rnar Luteberget <luteberget@gmail.com>"]

[dependencies]
clap = "*"
failure = "*"
failure_derive = "*"
z3 = "*"
rolling = {path = "../rolling" }
serde_json = "*"
svg = "*"

[lib]
crate-type=["rlib","staticlib"]

